CREATE TABLE image (
    id          UUID         PRIMARY KEY,
    storage_key VARCHAR(512) NOT NULL UNIQUE,
    mime_type   VARCHAR(100) NOT NULL,
    width       INTEGER      NOT NULL,
    height      INTEGER      NOT NULL,
    hash        CHAR(64)     NOT NULL UNIQUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE admin (
    id            UUID         PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(72)  NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE product (
    id         UUID          PRIMARY KEY,
    name       VARCHAR(120)  NOT NULL,
    price      NUMERIC(12,2) NOT NULL CHECK (price > 0),
    image_id   UUID          REFERENCES image (id),
    active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE orders (
    id                   UUID          PRIMARY KEY,
    seq                  BIGINT        GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
    status               VARCHAR(20)   NOT NULL,
    total                NUMERIC(12,2) NOT NULL CHECK (total > 0),
    payment_provider     VARCHAR(50)   NOT NULL,
    provider_payment_id  VARCHAR(120),
    payment_payload      TEXT,
    payment_qr_base64    TEXT,
    payment_checkout_url VARCHAR(1024),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    paid_at              TIMESTAMP WITH TIME ZONE,
    paid_manually_by     UUID          REFERENCES admin (id)
);

CREATE INDEX idx_orders_status_expires ON orders (status, expires_at);
CREATE INDEX idx_orders_paid_at        ON orders (paid_at);
CREATE INDEX idx_orders_provider_payment ON orders (payment_provider, provider_payment_id);

CREATE TABLE order_item (
    id           UUID          PRIMARY KEY,
    order_id     UUID          NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id   UUID          NOT NULL REFERENCES product (id),
    product_name VARCHAR(120)  NOT NULL,
    unit_price   NUMERIC(12,2) NOT NULL CHECK (unit_price > 0),
    quantity     INTEGER       NOT NULL CHECK (quantity > 0)
);

CREATE INDEX idx_order_item_order   ON order_item (order_id);
CREATE INDEX idx_order_item_product ON order_item (product_id);

CREATE TABLE expense (
    id          UUID          PRIMARY KEY,
    description VARCHAR(255)  NOT NULL,
    amount      NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    incurred_on DATE          NOT NULL,
    created_by  UUID          REFERENCES admin (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE settings (
    id               SMALLINT      PRIMARY KEY CHECK (id = 1),
    goal_target      NUMERIC(12,2) NOT NULL CHECK (goal_target > 0),
    crowdfunding_url VARCHAR(1024),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO settings (id, goal_target, crowdfunding_url, updated_at)
VALUES (1, 2000.00, NULL, CURRENT_TIMESTAMP);

CREATE TABLE webhook_event (
    id                  UUID         PRIMARY KEY,
    provider            VARCHAR(50)  NOT NULL,
    provider_event_id   VARCHAR(120),
    provider_payment_id VARCHAR(120),
    payload             TEXT         NOT NULL,
    received_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at        TIMESTAMP WITH TIME ZONE,
    error               VARCHAR(1024)
);

CREATE INDEX idx_webhook_event_payment ON webhook_event (provider, provider_payment_id);
